### PR TITLE
Vishnuauth

### PR DESCRIPTION
**Pull request by vishtheshnu**
Merging the refactored auth.js

### CODE REVIEW

**Comment by ncheema** [comment]
there is pending pull request for auth.js which includes multiple changes. So I think we should wait for that request to approve first, and then you can add changes to refactored version and merge those changes before deleting auth. what you think @kkolli ?

**Comment by kkolli** [comment]
Well this is actually failing, I think the best course of action would be to first merge the auth that is currently working, since the frontend team needs it, and then we can push this refactored

**Comment by ncheema** [comment]
@kkolli I agree, could you take a look at latest auth pull request #74 
@vishtheshnu once the latest auth gets approved, please pull from development

**Comment by kkolli** [comment]
@ncheema @vishtheshnu I don't understand, it seems like there is already a pull request with all the refactoring done by another group member, why have this one?

**Comment by ncheema** [comment]
I think @jhorta pulled from @vishtheshnu branch(Referring to slack conversation).

**Comment by kkolli** [comment]
Okay so this pull request doesn't need to take place, we will merge your branch and then merge that

**Comment by ncheema** [comment]
I confirmed with @jhorta he pulled from @vishtheshnu branch. @kkolli sounds good

**Comment by kkolli** [comment]
@vishtheshnu I"m closing this

**Pull request closed without merging**
