### PR TITLE
added functionality to update admin password and email

### PR DESCRIPTION
**Pull request by ncheema**
Functionality for admin account to update email and password.

### CODE REVIEW

**Comment by kkolli** [comment]
Nice work, could you take out the console log statement and remove the statement var ad = new Authmodel();

**Comment by kkolli** [comment]
I believe you can do admin.generateHash, just double check

**Comment by ncheema** [comment]
@kkolli I removed the log and ad var, tested with admin.hash. All changes work

**Comment by kkolli** [comment]
looks good, cool!

**Pull request merged**
