### PR TITLE
Theme

### PR DESCRIPTION
**Pull request by xxvii27**
Added some mocha testing to the API.

### CODE REVIEW

**Comment by DylanMoz** [comment]
Looks good. Also make sure to test your routes. These only test that your schemas are correct.

**Comment by kkolli** [comment]
Great work Louis!

**Comment by eddie4941** [comment]
This build is failing due to the angular dependencies. @xxvii27 Im taking a look now.

**Comment by eddie4941** [comment]
Mergeing development branch into theme branch should solve the dependency issues. @xxvii27 . Try merging them. You'll have conflict issues in your test file. ill let you handle that tough.

**Pull request merged**
