### PR TITLE
Forms

### PR DESCRIPTION
**Pull request by DylanMoz**
Backend for saving form templates using AngularJS Form Builder plugin, as well as saving and retrieving patients' submitted form records.

### CODE REVIEW

**Comment by eddie4941** [comment]
This is failing of the the jshint linting.

**Comment by kkolli** [comment]
I think you outdone yourself on the testing! Very nice! You'll have a merge conflict after auth is done since the scheme will change

**Comment by DylanMoz** [comment]
Fixed the linting issues.

**Comment by ashih3213** [comment]
New stuff. Fixed my tests to work with auth. The tests that aren't passing are not mine. They are the tests for theme. This was painful

**Comment by DylanMoz** [comment]
New stuff. Fixed my tests to work with auth. The tests that aren't passing are not mine. They are the tests for theme. This was painful

**Comment by eddie4941** [comment]
Very nice work.

**Pull request merged**
