### PR TITLE
integrated form tool added modal functionality

### PR DESCRIPTION
**Pull request by whyao**
Integrated AngularJS Form Builder. Needs CSS work, but functionality is there!

### CODE REVIEW

**Comment by eddie4941** [comment]
We chaned how the html views get packaged when we build the app. Some of the paths to the directive templates might need to be changed for this to work. Try integrating dev branch and see if this still works.

**Comment by whyao** [comment]
I just merged origin/development and my branch. Can I get some more signoffs before I complete the pull request?

**Comment by eddie4941** [comment]
I have a feeling that this will not work after minification. I've yet to try it though. I'll update when I've I tried it.

**Comment by whyao** [comment]
@eddie4941 You mean the website?

**Comment by ktzhang** [comment]
gonna take a look at it now

**Pull request merged**
